/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#303030",
        "background": "#f9f9f9",
        "secondary-fixed": "#cbe6ff",
        "tertiary": "#000000",
        "error-red": "#FF3B30",
        "error": "#ba1a1a",
        "surface-dim": "#dadada",
        "tertiary-fixed-dim": "#c4c7c9",
        "outline-variant": "#cfc4c5",
        "inverse-primary": "#c6c6c6",
        "on-surface-variant": "#4c4546",
        "on-tertiary-fixed": "#181c1e",
        "on-tertiary-fixed-variant": "#434749",
        "primary-fixed": "#e2e2e2",
        "on-background": "#1b1b1b",
        "surface-variant": "#e2e2e2",
        "on-surface": "#1b1b1b",
        "surface-container": "#eeeeee",
        "primary-fixed-dim": "#c6c6c6",
        "tertiary-container": "#181c1e",
        "on-secondary-container": "#2d5e80",
        "on-error-container": "#93000a",
        "surface-blue": "#E1EEF9",
        "success-green": "#28CD41",
        "primary-container": "#1b1b1b",
        "surface-tint": "#5e5e5e",
        "secondary-container": "#a8d7ff",
        "on-error": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "on-primary-fixed-variant": "#474747",
        "primary": "#000000",
        "on-primary-fixed": "#1b1b1b",
        "accent-pink": "#FFB1C1",
        "surface-gray": "#F2F2F7",
        "outline": "#7e7576",
        "on-secondary-fixed-variant": "#144b6c",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#001e30",
        "surface-container-low": "#f3f3f3",
        "surface": "#f9f9f9",
        "on-tertiary-container": "#818486",
        "secondary-fixed-dim": "#9dccf3",
        "secondary": "#326385",
        "tertiary-fixed": "#e0e3e5",
        "surface-container-highest": "#e2e2e2",
        "inverse-on-surface": "#f1f1f1",
        "on-primary-container": "#848484",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9f9"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.25rem",
        "3xl": "1.75rem",
        full: "9999px"
      },
      spacing: {
        "stack-gap-sm": "12px",
        "container-padding": "24px",
        unit: "8px",
        "stack-gap-md": "20px",
        "grid-gutter": "16px",
        "safe-area-bottom": "env(safe-area-inset-bottom, 24px)"
      },
      fontFamily: {
        "headline-xl": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "numeric-display": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "numeric-display": ["20px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }]
      },
      boxShadow: {
        'ambient': '0 12px 30px -8px rgba(0, 0, 0, 0.03)',
        'ambient-hover': '0 16px 40px -8px rgba(0, 0, 0, 0.05)'
      }
    }
  },
  plugins: [],
}
